### ISSUE TITLE
Remove redundant comments

### ISSUE THREAD

**Issue by tonadev** [sugarlabs/bichos-activity#6]
### Explanation
When working on PR #5, I noticed that there are redundant comments. They are unnecessary, so they can be deleted.

### Example
* In Main.py  
```
#self.set_icon_from_file(os.path.join(BASE, "Iconos", "bichos.svg"))
```
* in Juego.py
```
  def __stop_timer(self, objeto):
        #objeto.disconnect_by_func(self.__update_edad)
        try:
```

**Comment by chimosky** [comment]
@tonadev if you can work on a fix, there's no need opening an issue.
